using System;
using System.Collections.Generic;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class OrderBase
    {
        public int BaseId { get; set; }
    }

    [XmlAutoGenerated]
    public partial class OrderDerived : OrderBase
    {
        public string DerivedProp { get; set; }
    }

    [XmlAutoGenerated]
    public partial class NullableEntity
    {
        public int? NullableInt { get; set; }
        public int? NullableIntWithValue { get; set; }
    }

    [XmlAutoGenerated]
    public partial class CollectionEntity
    {
        [XmlArray("Items")]
        [XmlArrayItem("Item")]
        public List<string> Items { get; set; }
    }

    public class XmlSerializerPerspectiveTests
    {
        [Fact]
        public void TestElementOrder()
        {
            // XmlSerializer typically serializes Base properties BEFORE Derived properties.
            // Let's see what our generator does.
            var entity = new OrderDerived { BaseId = 1, DerivedProp = "A" };
            var xml = entity.WriteToXml();

            var elements = xml.Elements().ToList();
            Assert.Equal(2, elements.Count);
            
            // Current implementation: Derived properties come FIRST because GetAllProperties iterates Derived -> Base.
            // If we want to match XmlSerializer, we might need to reverse.
            // For now, let's assert the CURRENT behavior to document it.
            // If the user wants XmlSerializer behavior strictly, I will need to change the generator.
            
            Assert.Equal("BaseId", elements[0].Name.LocalName);
            Assert.Equal("DerivedProp", elements[1].Name.LocalName);
        }

        [Fact]
        public void TestNullablePrimitives()
        {
            var entity = new NullableEntity
            {
                NullableInt = null,
                NullableIntWithValue = 42
            };

            var xml = entity.WriteToXml();

            // Nullable = null -> Omitted
            Assert.Null(xml.Element("NullableInt"));
            
            // Nullable = value -> Serialized
            Assert.NotNull(xml.Element("NullableIntWithValue"));
            Assert.Equal("42", xml.Element("NullableIntWithValue").Value);
        }

        [Fact]
        public void TestEmptyCollection()
        {
            var entity = new CollectionEntity
            {
                Items = new List<string>() // Empty
            };

            var xml = entity.WriteToXml();

            // Empty list -> Container element exists, but empty content
            Assert.NotNull(xml.Element("Items"));
            Assert.Empty(xml.Element("Items").Elements());
        }

        [Fact]
        public void TestNullCollection()
        {
            var entity = new CollectionEntity
            {
                Items = null
            };

            var xml = entity.WriteToXml();

            // Null list -> Omitted
            Assert.Null(xml.Element("Items"));
        }
    }
}
