using System;
using System.Collections.Generic;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    public enum UserStatus
    {
        Active,
        Inactive,
        Suspended
    }

    [XmlRoot("CustomUser")]
    [XmlAutoGenerated]
    public partial class AttributeUser
    {
        [XmlAttribute("id")]
        public int Id { get; set; }

        [XmlElement("FullName")]
        public string Name { get; set; }

        [XmlIgnore]
        public string InternalData { get; set; }

        [XmlFormat("yyyy-MM-dd")]
        public DateTime BirthDate { get; set; }

        [XmlFormat("HH:mm:ss")]
        public DateTime LoginTime { get; set; } // Using DateTime for TimeOnly simulation if needed, or just DateTime

        public UserStatus Status { get; set; }

        [XmlArray("Tags")]
        [XmlArrayItem("Tag")]
        public List<string> Tags { get; set; }

        [XmlElement("Role")]
        public List<string> Roles { get; set; } // Flat list

        public List<int> Scores { get; set; } // Implicit container
    }

    [XmlAutoGenerated]
    public partial class TextMessage
    {
        [XmlAttribute]
        public string Type { get; set; }

        [XmlText]
        public string Content { get; set; }
    }

    public class AttributesTests
    {
        [Fact]
        public void TestAllAttributes()
        {
            var user = new AttributeUser
            {
                Id = 101,
                Name = "Alice",
                InternalData = "Secret",
                BirthDate = new DateTime(1990, 5, 20),
                LoginTime = new DateTime(2023, 1, 1, 14, 30, 0),
                Status = UserStatus.Active,
                Tags = new List<string> { "developer", "admin" },
                Roles = new List<string> { "User", "Manager" },
                Scores = new List<int> { 95, 88 }
            };

            var xml = user.WriteToXml();

            // Verify Root Name
            Assert.Equal("CustomUser", xml.Name.LocalName);

            // Verify Attribute
            Assert.Equal("101", xml.Attribute("id")?.Value);

            // Verify Element Name Override
            Assert.Equal("Alice", xml.Element("FullName")?.Value);

            // Verify Ignore
            Assert.Null(xml.Element("InternalData"));

            // Verify DateTime Format
            Assert.Equal("1990-05-20", xml.Element("BirthDate")?.Value);
            Assert.Equal("14:30:00", xml.Element("LoginTime")?.Value);

            // Verify Enum
            Assert.Equal("Active", xml.Element("Status")?.Value);

            // Verify XmlArray
            var tags = xml.Element("Tags");
            Assert.NotNull(tags);
            Assert.Equal(2, tags.Elements("Tag").Count());

            // Verify Flat List
            var roles = xml.Elements("Role").ToList();
            Assert.Equal(2, roles.Count);
            Assert.Equal("User", roles[0].Value);

            // Verify Implicit List
            var scores = xml.Element("Scores");
            Assert.NotNull(scores);
            Assert.Equal(2, scores.Elements().Count());
        }

        [Fact]
        public void TestXmlText()
        {
            var msg = new TextMessage
            {
                Type = "Info",
                Content = "Hello World"
            };

            var xml = msg.WriteToXml();

            Assert.Equal("TextMessage", xml.Name.LocalName);
            Assert.Equal("Info", xml.Attribute("Type")?.Value);
            Assert.Equal("Hello World", xml.Value);
        }

        [Fact]
        public void TestReadAttributes()
        {
            var xml = new XElement("CustomUser",
                new XAttribute("id", "202"),
                new XElement("FullName", "Bob"),
                new XElement("InternalData", "ShouldBeIgnored"), // Should be ignored
                new XElement("BirthDate", "1985-10-15"),
                new XElement("LoginTime", "09:15:00"),
                new XElement("Status", "Inactive"),
                new XElement("Tags",
                    new XElement("Tag", "user"),
                    new XElement("Tag", "guest")
                ),
                new XElement("Role", "Viewer"),
                new XElement("Role", "Editor"),
                new XElement("Scores",
                    new XElement("int", "10"), // Implicit item name for primitives? Generator uses type name usually?
                    new XElement("int", "20")
                )
            );

            // Wait, for implicit list items of primitives, what does the generator produce?
            // In GenerateCollectionWrite:
            // if (IsPrimitive(itemType)) sb.AppendLine($"{parentVar}.Add(new XElement(\"{itemXmlName}\", item));");
            // itemXmlName fallback is itemType.Name.
            // For int, itemType.Name is "Int32".
            // Let's check generated code or adjust test expectation.
            // Actually, for primitives, XmlSerializer usually uses the type name, e.g. <int>10</int>.
            // My generator uses itemType.Name. For int, it's Int32.
            // Let's adjust the test XML to match "Int32" for now, or verify what Roslyn gives for Name.
            // Roslyn "Int32" -> "Int32".
            
            // Let's update the test XML to use "Int32" for Scores items.
            
            var xml2 = new XElement("CustomUser",
                new XAttribute("id", "202"),
                new XElement("FullName", "Bob"),
                new XElement("BirthDate", "1985-10-15"),
                new XElement("LoginTime", "09:15:00"),
                new XElement("Status", "Inactive"),
                new XElement("Tags",
                    new XElement("Tag", "user"),
                    new XElement("Tag", "guest")
                ),
                new XElement("Role", "Viewer"),
                new XElement("Role", "Editor"),
                new XElement("Scores",
                    new XElement("Int32", "10"),
                    new XElement("Int32", "20")
                )
            );

            var user = new AttributeUser();
            user.ReadFromXml(xml2);

            Assert.Equal(202, user.Id);
            Assert.Equal("Bob", user.Name);
            Assert.Null(user.InternalData); // Should remain null
            Assert.Equal(new DateTime(1985, 10, 15), user.BirthDate);
            Assert.Equal(UserStatus.Inactive, user.Status);
            
            Assert.Equal(2, user.Tags.Count);
            Assert.Equal("user", user.Tags[0]);
            
            Assert.Equal(2, user.Roles.Count);
            Assert.Equal("Viewer", user.Roles[0]);
            
            Assert.Equal(2, user.Scores.Count);
            Assert.Equal(10, user.Scores[0]);
        }
    }
}
