using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using Xunit;
using FluentAssertions;
using XmlSourceGenerator;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Stress
{
    #region Test Entities

    [XmlAutoGenerated]
    public partial class ThreadSafeEntity
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public DateTime Timestamp { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel1
    {
        public string Level1Data { get; set; }
        public DeepLevel2 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel2
    {
        public string Level2Data { get; set; }
        public DeepLevel3 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel3
    {
        public string Level3Data { get; set; }
        public DeepLevel4 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel4
    {
        public string Level4Data { get; set; }
        public DeepLevel5 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel5
    {
        public string Level5Data { get; set; }
        public DeepLevel6 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel6
    {
        public string Level6Data { get; set; }
        public DeepLevel7 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel7
    {
        public string Level7Data { get; set; }
        public DeepLevel8 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel8
    {
        public string Level8Data { get; set; }
        public DeepLevel9 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel9
    {
        public string Level9Data { get; set; }
        public DeepLevel10 Child { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DeepLevel10
    {
        public string Level10Data { get; set; }
    }

    #endregion

    public class ThreadSafetyAndStressTests
    {
        #region Thread Safety Tests

        [Fact]
        public async Task ConcurrentSerialization_ShouldProduceCorrectResults()
        {
            const int threadCount = 100;
            const int iterationsPerThread = 10;

            var tasks = new List<Task<List<XElement>>>();

            for (int t = 0; t < threadCount; t++)
            {
                int threadId = t;
                tasks.Add(Task.Run(() =>
                {
                    var results = new List<XElement>();
                    for (int i = 0; i < iterationsPerThread; i++)
                    {
                        var entity = new ThreadSafeEntity
                        {
                            Id = threadId * iterationsPerThread + i,
                            Data = $"Thread{threadId}_Item{i}",
                            Timestamp = DateTime.UtcNow
                        };

                        results.Add(entity.WriteToXml());
                    }
                    return results;
                }));
            }

            var allResults = await Task.WhenAll(tasks);

            // Verify all results
            allResults.Should().HaveCount(threadCount);
            var totalElements = allResults.SelectMany(r => r).ToList();
            totalElements.Should().HaveCount(threadCount * iterationsPerThread);

            // Verify unique IDs
            var ids = totalElements.Select(x => int.Parse(x.Element("Id").Value)).ToList();
            ids.Should().OnlyHaveUniqueItems();
        }

        [Fact]
        public async Task ConcurrentDeserialization_ShouldProduceCorrectResults()
        {
            const int threadCount = 100;
            const int itemsPerThread = 10;

            // Create test XML for each thread
            var testData = new List<List<XElement>>();
            for (int t = 0; t < threadCount; t++)
            {
                var threadData = new List<XElement>();
                for (int i = 0; i < itemsPerThread; i++)
                {
                    var xml = new XElement("ThreadSafeEntity",
                        new XElement("Id", t * itemsPerThread + i),
                        new XElement("Data", $"Thread{t}_Item{i}"),
                        new XElement("Timestamp", DateTime.UtcNow));
                    threadData.Add(xml);
                }
                testData.Add(threadData);
            }

            var tasks = new List<Task<List<ThreadSafeEntity>>>();

            for (int t = 0; t < threadCount; t++)
            {
                var threadXml = testData[t];
                tasks.Add(Task.Run(() =>
                {
                    var results = new List<ThreadSafeEntity>();
                    foreach (var xml in threadXml)
                    {
                        var entity = new ThreadSafeEntity();
                        entity.ReadFromXml(xml);
                        results.Add(entity);
                    }
                    return results;
                }));
            }

            var allResults = await Task.WhenAll(tasks);

            // Verify all results
            allResults.Should().HaveCount(threadCount);
            var totalEntities = allResults.SelectMany(r => r).ToList();
            totalEntities.Should().HaveCount(threadCount * itemsPerThread);

            // Verify unique IDs
            var ids = totalEntities.Select(e => e.Id).ToList();
            ids.Should().OnlyHaveUniqueItems();
        }

        [Fact]
        public async Task ConcurrentRoundTrip_ShouldMaintainDataIntegrity()
        {
            const int threadCount = 50;
            const int roundTripsPerThread = 20;

            var tasks = new List<Task<bool>>();

            for (int t = 0; t < threadCount; t++)
            {
                int threadId = t;
                tasks.Add(Task.Run(() =>
                {
                    for (int i = 0; i < roundTripsPerThread; i++)
                    {
                        var original = new ThreadSafeEntity
                        {
                            Id = threadId * roundTripsPerThread + i,
                            Data = $"Thread{threadId}_RoundTrip{i}",
                            Timestamp = DateTime.UtcNow
                        };

                        var xml = original.WriteToXml();
                        var deserialized = new ThreadSafeEntity();
                        deserialized.ReadFromXml(xml);

                        if (deserialized.Id != original.Id ||
                            deserialized.Data != original.Data)
                        {
                            return false;
                        }
                    }
                    return true;
                }));
            }

            var results = await Task.WhenAll(tasks);

            // All threads should report success
            results.Should().OnlyContain(r => r == true);
        }

        #endregion

        #region Stress Tests - Deep Object Graphs

        [Fact]
        public void DeepObjectGraph_10Levels_ShouldSerialize()
        {
            var deep = new DeepLevel1
            {
                Level1Data = "L1",
                Child = new DeepLevel2
                {
                    Level2Data = "L2",
                    Child = new DeepLevel3
                    {
                        Level3Data = "L3",
                        Child = new DeepLevel4
                        {
                            Level4Data = "L4",
                            Child = new DeepLevel5
                            {
                                Level5Data = "L5",
                                Child = new DeepLevel6
                                {
                                    Level6Data = "L6",
                                    Child = new DeepLevel7
                                    {
                                        Level7Data = "L7",
                                        Child = new DeepLevel8
                                        {
                                            Level8Data = "L8",
                                            Child = new DeepLevel9
                                            {
                                                Level9Data = "L9",
                                                Child = new DeepLevel10
                                                {
                                                    Level10Data = "L10"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            };

            var xml = deep.WriteToXml();

            // Verify depth
            xml.Should().NotBeNull();
            xml.Element("Child").Should().NotBeNull();
            xml.Element("Child")?.Element("Child").Should().NotBeNull();

            // Verify deepest level
            var level10 = xml.Descendants("Level10Data").FirstOrDefault();
            level10.Should().NotBeNull();
            level10?.Value.Should().Be("L10");
        }

        [Fact]
        public void DeepObjectGraph_10Levels_ShouldDeserialize()
        {
            var xml = new XElement("DeepLevel1",
                new XElement("Level1Data", "L1"),
                new XElement("Child",
                    new XElement("Level2Data", "L2"),
                    new XElement("Child",
                        new XElement("Level3Data", "L3"),
                        new XElement("Child",
                            new XElement("Level4Data", "L4"),
                            new XElement("Child",
                                new XElement("Level5Data", "L5"),
                                new XElement("Child",
                                    new XElement("Level6Data", "L6"),
                                    new XElement("Child",
                                        new XElement("Level7Data", "L7"),
                                        new XElement("Child",
                                            new XElement("Level8Data", "L8"),
                                            new XElement("Child",
                                                new XElement("Level9Data", "L9"),
                                                new XElement("Child",
                                                    new XElement("Level10Data", "L10")))))))))));

            var entity = new DeepLevel1();
            entity.ReadFromXml(xml);

            // Verify all levels
            entity.Level1Data.Should().Be("L1");
            entity.Child.Should().NotBeNull();
            entity.Child.Level2Data.Should().Be("L2");
            entity.Child.Child.Should().NotBeNull();
            entity.Child.Child.Level3Data.Should().Be("L3");
            entity.Child.Child.Child.Child.Child.Child.Child.Child.Child.Should().NotBeNull();
            entity.Child.Child.Child.Child.Child.Child.Child.Child.Child.Level10Data.Should().Be("L10");
        }

        [Fact]
        public void DeepObjectGraph_RoundTrip_ShouldMaintainStructure()
        {
            var original = CreateDeepGraph();

            var xml = original.WriteToXml();
            var deserialized = new DeepLevel1();
            deserialized.ReadFromXml(xml);

            VerifyDeepGraph(deserialized);
        }

        private DeepLevel1 CreateDeepGraph()
        {
            return new DeepLevel1
            {
                Level1Data = "Data1",
                Child = new DeepLevel2
                {
                    Level2Data = "Data2",
                    Child = new DeepLevel3
                    {
                        Level3Data = "Data3",
                        Child = new DeepLevel4
                        {
                            Level4Data = "Data4",
                            Child = new DeepLevel5
                            {
                                Level5Data = "Data5",
                                Child = new DeepLevel6
                                {
                                    Level6Data = "Data6",
                                    Child = new DeepLevel7
                                    {
                                        Level7Data = "Data7",
                                        Child = new DeepLevel8
                                        {
                                            Level8Data = "Data8",
                                            Child = new DeepLevel9
                                            {
                                                Level9Data = "Data9",
                                                Child = new DeepLevel10
                                                {
                                                    Level10Data = "Data10"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            };
        }

        private void VerifyDeepGraph(DeepLevel1 entity)
        {
            entity.Level1Data.Should().Be("Data1");
            entity.Child.Level2Data.Should().Be("Data2");
            entity.Child.Child.Level3Data.Should().Be("Data3");
            entity.Child.Child.Child.Level4Data.Should().Be("Data4");
            entity.Child.Child.Child.Child.Level5Data.Should().Be("Data5");
            entity.Child.Child.Child.Child.Child.Level6Data.Should().Be("Data6");
            entity.Child.Child.Child.Child.Child.Child.Level7Data.Should().Be("Data7");
            entity.Child.Child.Child.Child.Child.Child.Child.Level8Data.Should().Be("Data8");
            entity.Child.Child.Child.Child.Child.Child.Child.Child.Level9Data.Should().Be("Data9");
            entity.Child.Child.Child.Child.Child.Child.Child.Child.Child.Level10Data.Should().Be("Data10");
        }

        #endregion

        #region Stress Tests - Large Collections

        [Fact]
        public void LargeCollection_1000Items_ShouldSerialize()
        {
            var entities = new List<ThreadSafeEntity>();
            for (int i = 0; i < 1000; i++)
            {
                entities.Add(new ThreadSafeEntity
                {
                    Id = i,
                    Data = $"Item_{i}",
                    Timestamp = DateTime.UtcNow.AddSeconds(i)
                });
            }

            var root = new XElement("Root");
            foreach (var entity in entities)
            {
                root.Add(entity.WriteToXml());
            }

            root.Elements().Should().HaveCount(1000);
        }

        [Fact]
        public void LargeCollection_1000Items_ShouldDeserialize()
        {
            var root = new XElement("Root");
            for (int i = 0; i < 1000; i++)
            {
                root.Add(new XElement("ThreadSafeEntity",
                    new XElement("Id", i),
                    new XElement("Data", $"Item_{i}"),
                    new XElement("Timestamp", DateTime.UtcNow.AddSeconds(i))));
            }

            var results = new List<ThreadSafeEntity>();
            foreach (var element in root.Elements())
            {
                var entity = new ThreadSafeEntity();
                entity.ReadFromXml(element);
                results.Add(entity);
            }

            results.Should().HaveCount(1000);
            results.Select(r => r.Id).Should().OnlyHaveUniqueItems();
        }

        #endregion
    }
}
