using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Xunit;
using XmlSourceGenerator.Analyzers;

namespace XmlSourceGenerator.UnitTests.Analyzers
{
    public class XmlUsageAnalyzerTests
    {
        [Fact]
        public async Task XSG006_ShouldReportWarning_ForComplexTypeWithoutAttribute()
        {
            var testCode = @"
using XmlSourceGenerator.Abstractions;

[XmlAutoGenerated]
public partial class TestClass
{
    public ComplexType Prop { get; set; }
}

public class ComplexType { }
";

            var expected = Verify.Diagnostic("XSG006")
                .WithSpan(7, 24, 7, 28) // Location of 'Prop'
                .WithArguments("Prop", "ComplexType")
                .WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning);

            await Verify.VerifyAnalyzerAsync(testCode, expected);
        }

        [Fact]
        public async Task XSG006_ShouldNotReport_ForPrimitiveTypes()
        {
            var testCode = @"
using System;
using XmlSourceGenerator.Abstractions;

[XmlAutoGenerated]
public partial class TestClass
{
    public int IntProp { get; set; }
    public string StringProp { get; set; }
    public DateTime DateProp { get; set; }
}
";
            await Verify.VerifyAnalyzerAsync(testCode);
        }

        [Fact]
        public async Task XSG006_ShouldNotReport_ForXmlAutoGeneratedTypes()
        {
            var testCode = @"
using XmlSourceGenerator.Abstractions;

[XmlAutoGenerated]
public partial class TestClass
{
    public NestedType Nested { get; set; }
}

[XmlAutoGenerated]
public partial class NestedType { }
";
            await Verify.VerifyAnalyzerAsync(testCode);
        }

        [Fact]
        public async Task XSG006_ShouldReportWarning_ForListElement_NotListItself()
        {
            var testCode = @"
using System.Collections.Generic;
using XmlSourceGenerator.Abstractions;

[XmlAutoGenerated]
public partial class TestClass
{
    public List<ComplexType> Prop { get; set; }
}

public class ComplexType { }
";

            // Warning should be about 'ComplexType', not 'List'
            var expected = Verify.Diagnostic("XSG006")
                .WithSpan(8, 30, 8, 34) // Location of 'Prop'
                .WithArguments("Prop", "ComplexType")
                .WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Warning);

            await Verify.VerifyAnalyzerAsync(testCode, expected);
        }
        [Fact]
        public async Task XSG006_ShouldNotReport_ForXElement()
        {
            var testCode = @"
using System.Xml.Linq;
using XmlSourceGenerator.Abstractions;

[XmlAutoGenerated]
public partial class TestClass
{
    public XElement ExtraVars { get; set; }
}
";
            await Verify.VerifyAnalyzerAsync(testCode);
        }
    }

    public static class Verify
    {
        public static DiagnosticResult Diagnostic(string id) => new DiagnosticResult(id, Microsoft.CodeAnalysis.DiagnosticSeverity.Warning);

        public static async Task VerifyAnalyzerAsync(string source, params DiagnosticResult[] expected)
        {
            var test = new CSharpAnalyzerTest<XmlUsageAnalyzer, XUnitVerifier>
            {
                TestCode = source,
                ReferenceAssemblies = ReferenceAssemblies.Net.Net60 // Use .NET 6 reference assemblies
            };

            // Add Abstractions reference
            test.TestState.AdditionalReferences.Add(typeof(XmlSourceGenerator.Abstractions.XmlAutoGeneratedAttribute).Assembly);
            test.TestState.AdditionalReferences.Add(typeof(System.Xml.Linq.XElement).Assembly);

            test.ExpectedDiagnostics.AddRange(expected);
            await test.RunAsync();
        }
    }
}
