using Microsoft.CodeAnalysis;

namespace XmlSourceGenerator.Analyzers
{
    internal static class Diagnostics
    {
        public static readonly DiagnosticDescriptor ClassMustBePartial = new DiagnosticDescriptor(
            id: "XSG001",
            title: "Class must be partial",
            messageFormat: "Class '{0}' marked with [XmlAutoGenerated] must be partial",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor ClassMustHaveParameterlessConstructor = new DiagnosticDescriptor(
            id: "XSG002",
            title: "Class must have a parameterless constructor",
            messageFormat: "Class '{0}' marked with [XmlAutoGenerated] must have a public parameterless constructor",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor XmlAttributeOnComplexType = new DiagnosticDescriptor(
            id: "XSG003",
            title: "[XmlAttribute] used on complex type",
            messageFormat: "Property '{0}' cannot be marked with [XmlAttribute] because it is a complex type. Only primitives, enums, strings, and DateTime types are supported",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor XmlListElementOnNonCollection = new DiagnosticDescriptor(
            id: "XSG004",
            title: "[XmlStreamListElement] used on non-collection type",
            messageFormat: "Property '{0}' cannot be marked with [XmlStreamListElement] because it is not a collection type",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor DuplicateXmlName = new DiagnosticDescriptor(
            id: "XSG005",
            title: "Duplicate XML name",
            messageFormat: "The XML name '{0}' is used by multiple properties in class '{1}'",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor ReflectionFallbackWarning = new DiagnosticDescriptor(
            id: "XSG006",
            title: "Reflection fallback used",
            messageFormat: "Property '{0}' of type '{1}' will use reflection for serialization. Mark type '{1}' with [XmlAutoGenerated] to use source generation",
            category: "Performance",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true);
    }
}
