namespace XmlSourceGenerator.Abstractions
{
    /// <summary>
    /// Marks a class for automatic IXmlStreamable implementation generation.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public class XmlAutoGeneratedAttribute : Attribute
    {
    }

    /// <summary>
    /// Maps a specific XML element name to a type for polymorphic lists.
    /// Usage: [XmlStreamListElement("TAG_NAME", typeof(MyClass))]
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = true)]
    public class XmlStreamListElementAttribute : Attribute
    {
        public string ElementName { get; }
        public Type TargetType { get; }

        public XmlStreamListElementAttribute(string elementName, Type targetType)
        {
            ElementName = elementName;
            TargetType = targetType;
        }
    }

    /// <summary>
    /// Specifies format strings for parsing and serializing types like DateTime, DateOnly, TimeOnly, etc.
    /// First format is used for writing. All formats are tried for reading.
    /// Usage: [XmlFormat("yyyy-MM-dd", "MM/dd/yyyy")] // Write: ISO, Read: ISO or US
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlFormatAttribute : Attribute
    {
        public string[] Formats { get; }

        public XmlFormatAttribute(params string[] formats)
        {
            Formats = formats ?? new[] { "o" }; // Default to round-trip format
        }
    }

    /// <summary>
    /// Excludes a property from XML serialization.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlIgnoreAttribute : Attribute
    {
    }

    /// <summary>
    /// Specifies a custom XML element name for a property.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlElementAttribute : Attribute
    {
        public string? ElementName { get; set; }
        public string? Namespace { get; set; }
        public Type? Type { get; set; }
        public bool IsNullable { get; set; }
        public int Order { get; set; } = -1;

        public XmlElementAttribute()
        {
        }

        public XmlElementAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Serializes a property as an XML attribute instead of an element.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlAttributeAttribute : Attribute
    {
        public string? AttributeName { get; set; }
        public string? Namespace { get; set; }

        public XmlAttributeAttribute()
        {
        }

        public XmlAttributeAttribute(string? attributeName = null)
        {
            AttributeName = attributeName;
        }
    }

    /// <summary>
    /// Specifies a custom root element name for the class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public class XmlRootAttribute : Attribute
    {
        public string? ElementName { get; set; }
        public string? Namespace { get; set; }
        public bool IsNullable { get; set; }

        public XmlRootAttribute()
        {
        }

        public XmlRootAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Serializes a property as the inner text of the XML element.
    /// Only one property per class can have this attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlTextAttribute : Attribute
    {
    }

    /// <summary>
    /// Wraps a collection in a container element.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlArrayAttribute : Attribute
    {
        public string? ElementName { get; set; }
        public string? Namespace { get; set; }
        public bool IsNullable { get; set; }
        public int Order { get; set; } = -1;

        public XmlArrayAttribute()
        {
        }

        public XmlArrayAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Specifies the element name for individual items in an array.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlArrayItemAttribute : Attribute
    {
        public string? ElementName { get; set; }
        public string? Namespace { get; set; }
        public Type? Type { get; set; }
        public bool IsNullable { get; set; }

        public XmlArrayItemAttribute()
        {
        }

        public XmlArrayItemAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Serializes a property as a sequence of XML elements that do not map to a specific member.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlAnyElementAttribute : Attribute
    {
        public string? Name { get; set; }
        public string? Namespace { get; set; }
        public int Order { get; set; } = -1;
        
        public XmlAnyElementAttribute(string? name = null)
        {
            Name = name;
        }
    }

    /// <summary>
    /// Serializes a property as a sequence of XML attributes that do not map to a specific member.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlAnyAttributeAttribute : Attribute
    {
    }

    /// <summary>
    /// Controls how an enum member is serialized.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    public class XmlEnumAttribute : Attribute
    {
        public string? Name { get; set; }

        public XmlEnumAttribute(string? name = null)
        {
            Name = name;
        }
    }

    /// <summary>
    /// Allows the serializer to recognize a type when it serializes an object.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface | AttributeTargets.Method, Inherited = true, AllowMultiple = true)]
    public class XmlIncludeAttribute : Attribute
    {
        public Type Type { get; }

        public XmlIncludeAttribute(Type type)
        {
            Type = type;
        }
    }

    /// <summary>
    /// Controls the XML schema that is generated when the attribute target is serialized.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
    public class XmlTypeAttribute : Attribute
    {
        public string? TypeName { get; set; }
        public string? Namespace { get; set; }
        public bool AnonymousType { get; set; }
        public bool IncludeInSchema { get; set; }

        public XmlTypeAttribute(string? typeName = null)
        {
            TypeName = typeName;
        }
    }
}
