using System;

namespace SourceGeneratorUtils
{
    /// <summary>
    /// Marks a class for automatic IXmlStreamable implementation generation.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public class XmlAutoGeneratedAttribute : Attribute
    {
    }

    /// <summary>
    /// Maps a specific XML element name to a type for polymorphic lists.
    /// Usage: [XmlStreamListElement("TAG_NAME", typeof(MyClass))]
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = true)]
    public class XmlStreamListElementAttribute : Attribute
    {
        public string ElementName { get; }
        public Type TargetType { get; }

        public XmlStreamListElementAttribute(string elementName, Type targetType)
        {
            ElementName = elementName;
            TargetType = targetType;
        }
    }

    /// <summary>
    /// Specifies format strings for parsing and serializing types like DateTime, DateOnly, TimeOnly, etc.
    /// First format is used for writing. All formats are tried for reading.
    /// Usage: [XmlFormat("yyyy-MM-dd", "MM/dd/yyyy")] // Write: ISO, Read: ISO or US
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlFormatAttribute : Attribute
    {
        public string[] Formats { get; }

        public XmlFormatAttribute(params string[] formats)
        {
            Formats = formats ?? new[] { "o" }; // Default to round-trip format
        }
    }

    /// <summary>
    /// Excludes a property from XML serialization.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlIgnoreAttribute : Attribute
    {
    }

    /// <summary>
    /// Specifies a custom XML element name for a property.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlElementAttribute : Attribute
    {
        public string ElementName { get; }
        public string? Namespace { get; set; }

        public XmlElementAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Serializes a property as an XML attribute instead of an element.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlAttributeAttribute : Attribute
    {
        public string? AttributeName { get; }

        public XmlAttributeAttribute(string? attributeName = null)
        {
            AttributeName = attributeName;
        }
    }

    /// <summary>
    /// Specifies a custom root element name for the class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public class XmlRootAttribute : Attribute
    {
        public string ElementName { get; }
        public string? Namespace { get; set; }

        public XmlRootAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Serializes a property as the inner text of the XML element.
    /// Only one property per class can have this attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlTextAttribute : Attribute
    {
    }

    /// <summary>
    /// Wraps a collection in a container element.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlArrayAttribute : Attribute
    {
        public string ElementName { get; }

        public XmlArrayAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }

    /// <summary>
    /// Specifies the element name for individual items in an array.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    public class XmlArrayItemAttribute : Attribute
    {
        public string ElementName { get; }

        public XmlArrayItemAttribute(string elementName)
        {
            ElementName = elementName;
        }
    }
}
