using System;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class CasingEntity
    {
        public string FirstName { get; set; }
        public int UserAge { get; set; }
        public bool IsActiveUser { get; set; }
    }

    [XmlAutoGenerated]
    public partial class PrimitivesEntity
    {
        public int IntValue { get; set; }
        public double DoubleValue { get; set; }
        public bool BoolValue { get; set; }
        public decimal DecimalValue { get; set; }
        public float FloatValue { get; set; }
        public long LongValue { get; set; }
    }

    public class IsolationTests
    {
        [Fact]
        public void TestCamelCasePolicy()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.CamelCase
            };

            var entity = new CasingEntity
            {
                FirstName = "John",
                UserAge = 30,
                IsActiveUser = true
            };

            var xml = entity.WriteToXml(options);

            Assert.NotNull(xml.Element("firstName"));
            Assert.NotNull(xml.Element("userAge"));
            Assert.NotNull(xml.Element("isActiveUser"));
            
            Assert.Equal("John", xml.Element("firstName").Value);
        }

        [Fact]
        public void TestSnakeCasePolicy()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.SnakeCase
            };

            var entity = new CasingEntity
            {
                FirstName = "John",
                UserAge = 30,
                IsActiveUser = true
            };

            var xml = entity.WriteToXml(options);

            Assert.NotNull(xml.Element("first_name"));
            Assert.NotNull(xml.Element("user_age"));
            Assert.NotNull(xml.Element("is_active_user"));
            
            Assert.Equal("John", xml.Element("first_name").Value);
        }

        [Fact]
        public void TestPrimitiveParsing()
        {
            var xml = new XElement("PrimitivesEntity",
                new XElement("IntValue", "2147483647"),
                new XElement("DoubleValue", "123.456"),
                new XElement("BoolValue", "true"),
                new XElement("DecimalValue", "789.012"),
                new XElement("FloatValue", "45.67"),
                new XElement("LongValue", "9223372036854775807")
            );

            var entity = new PrimitivesEntity();
            entity.ReadFromXml(xml);

            Assert.Equal(int.MaxValue, entity.IntValue);
            Assert.Equal(123.456, entity.DoubleValue);
            Assert.True(entity.BoolValue);
            Assert.Equal(789.012m, entity.DecimalValue);
            Assert.Equal(45.67f, entity.FloatValue);
            Assert.Equal(long.MaxValue, entity.LongValue);
        }

        [Fact]
        public void TestPrimitiveParsing_EdgeCases()
        {
            // Test with different boolean casing and numeric formatting if supported by XElement casting
            // XElement casting to bool supports "true"/"false" (case sensitive? actually XML standard is lowercase, but .NET might be flexible)
            // Let's verify standard XML behavior.
            
            var xml = new XElement("PrimitivesEntity",
                new XElement("IntValue", "-1"),
                new XElement("DoubleValue", "-0.001"),
                new XElement("BoolValue", "false"), 
                new XElement("DecimalValue", "0"),
                new XElement("FloatValue", "0"),
                new XElement("LongValue", "0")
            );

            var entity = new PrimitivesEntity();
            entity.ReadFromXml(xml);

            Assert.Equal(-1, entity.IntValue);
            Assert.Equal(-0.001, entity.DoubleValue);
            Assert.False(entity.BoolValue);
        }
    }
}
