using System;
using System.Xml.Linq;
using Xunit;
using XmlSourceGenerator;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class VirtualBase
    {
        [XmlElement("BaseName")]
        public virtual string Name { get; set; }

        public virtual int Value { get; set; }
    }

    [XmlAutoGenerated]
    public partial class OverriddenDerived : VirtualBase
    {
        // Override and rename
        [XmlElement("OverriddenName")]
        public override string Name { get; set; }

        // Override and ignore
        [XmlIgnore]
        public override int Value { get; set; }
    }

    [XmlAutoGenerated]
    public partial class HidingDerived : VirtualBase
    {
        // Hide with 'new' and rename
        [XmlElement("HiddenName")]
        public new string Name { get; set; }
    }

    public class OverrideTests
    {
        [Fact]
        public void TestOverriddenProperty_Rename()
        {
            var entity = new OverriddenDerived
            {
                Name = "TestName",
                Value = 123
            };

            var xml = entity.WriteToXml();

            // Should use the attribute from the derived class
            Assert.NotNull(xml.Element("OverriddenName"));
            Assert.Equal("TestName", xml.Element("OverriddenName").Value);
            
            // Should NOT use the base class attribute name
            Assert.Null(xml.Element("BaseName"));
        }

        [Fact]
        public void TestOverriddenProperty_Ignore()
        {
            var entity = new OverriddenDerived
            {
                Name = "TestName",
                Value = 123
            };

            var xml = entity.WriteToXml();

            // Value is ignored in derived class
            Assert.Null(xml.Element("Value"));
        }

        [Fact]
        public void TestHiddenProperty_New()
        {
            var entity = new HidingDerived
            {
                Name = "HiddenValue"
            };

            var xml = entity.WriteToXml();

            // Should use the 'new' property attribute
            Assert.NotNull(xml.Element("HiddenName"));
            Assert.Equal("HiddenValue", xml.Element("HiddenName").Value);
            
            // Should NOT use the base class attribute name
            Assert.Null(xml.Element("BaseName"));
        }

        [Fact]
        public void TestPolymorphicRead_Override()
        {
            var xml = new XElement("OverriddenDerived",
                new XElement("OverriddenName", "ReadTest"),
                new XElement("Value", "999") // Should be ignored
            );

            var entity = new OverriddenDerived();
            entity.ReadFromXml(xml);

            Assert.Equal("ReadTest", entity.Name);
            Assert.Equal(0, entity.Value); // Default because ignored
        }
    }
}
