using System;
using System.Collections.Generic;
using System.Xml.Linq;
using Xunit;
using XmlSourceGenerator;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Features
{
    [XmlAutoGenerated]
    public partial class GenBase
    {
        public string BaseProp { get; set; }
    }

    // Missing [XmlAutoGenerated]
    public class DerivedNoGen : GenBase
    {
        public string DerivedProp { get; set; }
    }

    [XmlAutoGenerated]
    public partial class ContainerGen
    {
        public DerivedNoGen Inner { get; set; }
    }

    public class ReproductionTests
    {
        [Fact]
        public void TestInheritanceDataLoss()
        {
            var item = new DerivedNoGen
            {
                BaseProp = "Base",
                DerivedProp = "Derived"
            };

            // DerivedNoGen doesn't have WriteToXml, so we cast to base or use wrapper if we could, 
            // but normally we use it in a container or via extension if generated?
            // Wait, if it's not generated, it doesn't have the method. 
            // So we can't call item.WriteToXml() directly unless we cast to GenBase (if GenBase has it).
            // GenBase has it.
            
            var xml = ((GenBase)item).WriteToXml();
            
            // Current behavior (Bug): DerivedProp is missing because GenBase.WriteToXml doesn't know about it.
            Assert.Equal("Base", xml.Element("BaseProp")?.Value);
            
            // This is the data loss:
            Assert.Null(xml.Element("DerivedProp")); 
        }

        [Fact]
        public void TestNestedDataLoss()
        {
            var container = new ContainerGen
            {
                Inner = new DerivedNoGen
                {
                    BaseProp = "Base",
                    DerivedProp = "Derived"
                }
            };

            var xml = container.WriteToXml();
            
            var inner = xml.Element("Inner");
            Assert.NotNull(inner);
            Assert.Equal("Base", inner.Element("BaseProp")?.Value);
            
            // This is the data loss:
            Assert.Null(inner.Element("DerivedProp"));
        }
    }
}
