using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration.Features
{
    public partial class XmlAnyTests
    {
        [XmlAutoGenerated]
        public partial class AnyContainer
        {
            public string Name { get; set; }

            [XmlAnyElement]
            public List<XElement> AnyElements { get; set; }

            [XmlAnyAttribute]
            public List<XAttribute> AnyAttributes { get; set; }
        }

        [Fact]
        public void XmlAny_SerializesExtraContent()
        {
            var container = new AnyContainer
            {
                Name = "Main",
                AnyElements = new List<XElement>
                {
                    new XElement("Extra", "Data"),
                    new XElement("More", "Info")
                },
                AnyAttributes = new List<XAttribute>
                {
                    new XAttribute("Attr1", "Val1"),
                    new XAttribute("Attr2", "Val2")
                }
            };

            var xml = container.WriteToXml();

            Assert.Equal("Main", xml.Element("Name")?.Value);
            Assert.Equal("Data", xml.Element("Extra")?.Value);
            Assert.Equal("Info", xml.Element("More")?.Value);
            Assert.Equal("Val1", xml.Attribute("Attr1")?.Value);
            Assert.Equal("Val2", xml.Attribute("Attr2")?.Value);
        }

        [Fact]
        public void XmlAny_DeserializesExtraContent()
        {
            var xml = XElement.Parse(@"
                <AnyContainer Attr1=""Val1"" Attr2=""Val2"">
                    <Name>Main</Name>
                    <Extra>Data</Extra>
                    <More>Info</More>
                </AnyContainer>");

            var container = new AnyContainer();
            container.ReadFromXml(xml);

            Assert.Equal("Main", container.Name);
            
            Assert.NotNull(container.AnyElements);
            Assert.Equal(2, container.AnyElements.Count);
            Assert.Contains(container.AnyElements, e => e.Name == "Extra" && e.Value == "Data");
            Assert.Contains(container.AnyElements, e => e.Name == "More" && e.Value == "Info");

            Assert.NotNull(container.AnyAttributes);
            Assert.Equal(2, container.AnyAttributes.Count);
            Assert.Contains(container.AnyAttributes, a => a.Name == "Attr1" && a.Value == "Val1");
            Assert.Contains(container.AnyAttributes, a => a.Name == "Attr2" && a.Value == "Val2");
        }
    }
}
