using System;
using Xunit;
using System.Xml.Linq;
using XmlSourceGenerator;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Integration.Features
{
    public partial class XmlEnumTests
    {
        public enum Status
        {
            [XmlEnum("active")]
            Active,
            [XmlEnum("inactive")]
            Inactive,
            [XmlEnum("pending")]
            Pending
        }

        [XmlAutoGenerated]
        public partial class UserAccount
        {
            public string Username { get; set; }
            public Status AccountStatus { get; set; }
        }

        [Fact]
        public void XmlEnum_SerializesWithCustomValue_Active()
        {
            var account = new UserAccount 
            { 
                Username = "john",
                AccountStatus = Status.Active 
            };
            
            var xml = account.WriteToXml();
            
            Assert.Equal("active", xml.Element("AccountStatus")?.Value);
        }

        [Fact]
        public void XmlEnum_SerializesWithCustomValue_Inactive()
        {
            var account = new UserAccount 
            { 
                Username = "jane",
                AccountStatus = Status.Inactive
            };
            
            var xml = account.WriteToXml();
            
            Assert.Equal("inactive", xml.Element("AccountStatus")?.Value);
        }

        [Fact]
        public void XmlEnum_DeserializesFromCustomValue_Active()
        {
            var xml = XElement.Parse(@"
                <UserAccount>
                    <Username>john</Username>
                    <AccountStatus>active</AccountStatus>
                </UserAccount>");

            var account = new UserAccount();
            account.ReadFromXml(xml);

            Assert.Equal(Status.Active, account.AccountStatus);
        }

        [Fact]
        public void XmlEnum_DeserializesFromCustomValue_Pending()
        {
            var xml = XElement.Parse(@"
                <UserAccount>
                    <Username>bob</Username>
                    <AccountStatus>pending</AccountStatus>
                </UserAccount>");

            var account = new UserAccount();
            account.ReadFromXml(xml);

            Assert.Equal(Status.Pending, account.AccountStatus);
        }

        [Fact]
        public void XmlEnum_RoundTrip_PreservesCustomValues()
        {
            var original = new UserAccount 
            { 
                Username = "test",
                AccountStatus = Status.Inactive
            };
            
            var xml = original.WriteToXml();
            var deserialized = new UserAccount();
            deserialized.ReadFromXml(xml);

            Assert.Equal(original.Username, deserialized.Username);
            Assert.Equal(original.AccountStatus, deserialized.AccountStatus);
            Assert.Equal("inactive", xml.Element("AccountStatus")?.Value);
        }
    }
}
