using System;
using Xunit;
using System.Xml.Linq;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration.Features
{
    public class XmlIncludeTests
    {
        [XmlInclude(typeof(Dog))]
        [XmlInclude(typeof(Cat))]
        [XmlAutoGenerated]
        public partial class Animal
        {
            public string Name { get; set; }
        }

        [XmlAutoGenerated]
        public partial class Dog : Animal
        {
            public bool CanBark { get; set; }
        }

        [XmlAutoGenerated]
        public partial class Cat : Animal
        {
            public int LivesRemaining { get; set; }
        }

        [Fact]
        public void XmlInclude_SerializesDerivedType_Dog()
        {
            var dog = new Dog { Name = "Buddy", CanBark = true };
            var xml = dog.WriteToXml();

            Assert.Equal("Dog", xml.Name.LocalName);
            Assert.Equal("Buddy", xml.Element("Name")?.Value);
            Assert.Equal("True", xml.Element("CanBark")?.Value);
        }

        [Fact]
        public void XmlInclude_SerializesDerivedType_Cat()
        {
            var cat = new Cat { Name = "Whiskers", LivesRemaining = 9 };
            var xml = cat.WriteToXml();

            Assert.Equal("Cat", xml.Name.LocalName);
            Assert.Equal("Whiskers", xml.Element("Name")?.Value);
            Assert.Equal("9", xml.Element("LivesRemaining")?.Value);
        }

        [Fact]
        public void XmlInclude_DeserializesDerivedType_Dog()
        {
            var xml = XElement.Parse(@"
                <Dog>
                    <Name>Buddy</Name>
                    <CanBark>True</CanBark>
                </Dog>");

            var dog = new Dog();
            dog.ReadFromXml(xml);

            Assert.Equal("Buddy", dog.Name);
            Assert.True(dog.CanBark);
        }

        [Fact]
        public void XmlInclude_DeserializesDerivedType_Cat()
        {
            var xml = XElement.Parse(@"
                <Cat>
                    <Name>Whiskers</Name>
                    <LivesRemaining>9</LivesRemaining>
                </Cat>");

            var cat = new Cat();
            cat.ReadFromXml(xml);

            Assert.Equal("Whiskers", cat.Name);
            Assert.Equal(9, cat.LivesRemaining);
        }
    }
}
