using System;
using System.IO;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class BasicUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Balance { get; set; }
        public bool IsActive { get; set; }
        public int? OptionalAge { get; set; }
    }

    public class BasicMappingTests
    {
        [Fact]
        public void TestIntMapping()
        {
            var xml = new XElement("BasicUser", new XElement("Id", 42));
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.Equal(42, user.Id);
        }

        [Fact]
        public void TestStringMapping()
        {
            var xml = new XElement("BasicUser", new XElement("Name", "John Doe"));
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.Equal("John Doe", user.Name);
        }

        [Fact]
        public void TestDoubleMapping()
        {
            var xml = new XElement("BasicUser", new XElement("Balance", "123.45"));
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.Equal(123.45, user.Balance);
        }

        [Fact]
        public void TestBoolMapping()
        {
            var xml = new XElement("BasicUser", new XElement("IsActive", "true"));
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.True(user.IsActive);
        }

        [Fact]
        public void TestNullableMapping_WithValue()
        {
            var xml = new XElement("BasicUser", new XElement("OptionalAge", "25"));
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.Equal(25, user.OptionalAge);
        }

        [Fact]
        public void TestNullableMapping_WithoutValue()
        {
            var xml = new XElement("BasicUser");
            var user = new BasicUser();
            user.ReadFromXml(xml);

            Assert.Null(user.OptionalAge);
        }

        [Fact]
        public void TestRoundTrip()
        {
            var original = new BasicUser
            {
                Id = 100,
                Name = "Jane",
                Balance = 999.99,
                IsActive = true,
                OptionalAge = 30
            };

            var xml = original.WriteToXml();
            var restored = new BasicUser();
            restored.ReadFromXml(xml);

            Assert.Equal(original.Id, restored.Id);
            Assert.Equal(original.Name, restored.Name);
            Assert.Equal(original.Balance, restored.Balance);
            Assert.Equal(original.IsActive, restored.IsActive);
            Assert.Equal(original.OptionalAge, restored.OptionalAge);
        }
    }
}
