using System.Collections.Generic;
using System.Xml.Linq;
using Xunit;
using XmlSourceGenerator;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class EdgeCaseEntity
    {
        public string Name { get; set; }
        public int Count { get; set; }
        public List<string> Tags { get; set; } = new();
    }

    public class EdgeCaseTests
    {
        [Fact]
        public void TestMissingElements()
        {
            var xml = new XElement("EdgeCaseEntity");
            var entity = new EdgeCaseEntity();
            entity.ReadFromXml(xml);

            Assert.Null(entity.Name);
            Assert.Equal(0, entity.Count);
        }

        [Fact]
        public void TestExtraElements()
        {
            var xml = new XElement("EdgeCaseEntity",
                new XElement("Name", "Test"),
                new XElement("UnknownField", "ShouldBeIgnored"),
                new XElement("Count", 5));

            var entity = new EdgeCaseEntity();
            
            // Should not throw
            entity.ReadFromXml(xml);

            Assert.Equal("Test", entity.Name);
            Assert.Equal(5, entity.Count);
        }

        [Fact]
        public void TestEmptyList()
        {
            var xml = new XElement("EdgeCaseEntity",
                new XElement("Name", "Empty"));

            var entity = new EdgeCaseEntity();
            entity.ReadFromXml(xml);

            Assert.NotNull(entity.Tags);
            Assert.Empty(entity.Tags);
        }

        [Fact]
        public void TestNullValues()
        {
            var entity = new EdgeCaseEntity
            {
                Name = null,
                Count = 0
            };

            var xml = entity.WriteToXml();

            // Null string should not be written
            Assert.Null(xml.Element("Name"));
            
            // Default int (0) should be written
            Assert.Equal("0", xml.Element("Count")?.Value);
        }
    }
}
