using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    // Case A: Base has [XmlAutoGenerated]
    [XmlAutoGenerated]
    public partial class BaseEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DerivedEntity : BaseEntity
    {
        public string Description { get; set; }
    }

    // Case B: Base does NOT have attribute
    public class PlainBaseEntity
    {
        public int BaseId { get; set; }
    }

    [XmlAutoGenerated]
    public partial class FlattenedEntity : PlainBaseEntity
    {
        public string ChildProperty { get; set; }
    }

    public class InheritanceTests
    {
        [Fact]
        public void TestInheritance_BaseHasAttribute()
        {
            var xml = new XElement("DerivedEntity",
                new XElement("Id", 1),
                new XElement("Name", "Base"),
                new XElement("Description", "Derived"));

            var entity = new DerivedEntity();
            entity.ReadFromXml(xml);

            Assert.Equal(1, entity.Id);
            Assert.Equal("Base", entity.Name);
            Assert.Equal("Derived", entity.Description);
        }

        [Fact]
        public void TestInheritance_BaseHasAttribute_Write()
        {
            var entity = new DerivedEntity
            {
                Id = 2,
                Name = "Test",
                Description = "Details"
            };

            var xml = entity.WriteToXml();

            Assert.Equal("2", xml.Element("Id")?.Value);
            Assert.Equal("Test", xml.Element("Name")?.Value);
            Assert.Equal("Details", xml.Element("Description")?.Value);
        }

        [Fact]
        public void TestInheritance_BaseNoAttribute()
        {
            var xml = new XElement("FlattenedEntity",
                new XElement("BaseId", 10),
                new XElement("ChildProperty", "Value"));

            var entity = new FlattenedEntity();
            entity.ReadFromXml(xml);

            Assert.Equal(10, entity.BaseId);
            Assert.Equal("Value", entity.ChildProperty);
        }

        [Fact]
        public void TestInheritance_WithOptions()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.CamelCase
            };

            var xml = new XElement("DerivedEntity",
                new XElement("id", 3),
                new XElement("name", "CamelTest"),
                new XElement("description", "CamelDesc"));

            var entity = new DerivedEntity();
            entity.ReadFromXml(xml, options);

            Assert.Equal(3, entity.Id);
            Assert.Equal("CamelTest", entity.Name);
            Assert.Equal("CamelDesc", entity.Description);
        }
    }
}
