using System.Xml.Linq;
using Xunit;
using FluentAssertions;
using XmlSourceGenerator.Abstractions;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Integration
{
    // Case A: Base has [XmlAutoGenerated]
    [XmlAutoGenerated]
    public partial class BaseEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    [XmlAutoGenerated]
    public partial class DerivedEntity : BaseEntity
    {
        public string Description { get; set; }
    }

    // Case B: Base does NOT have attribute
    public class PlainBaseEntity
    {
        public int BaseId { get; set; }
    }

    [XmlAutoGenerated]
    public partial class FlattenedEntity : PlainBaseEntity
    {
        public string ChildProperty { get; set; }
    }

    public class InheritanceTests
    {
        [Fact]
        public void TestInheritance_BaseHasAttribute()
        {
            var xml = new XElement("DerivedEntity",
                new XElement("Id", 1),
                new XElement("Name", "Base"),
                new XElement("Description", "Derived"));

            var entity = new DerivedEntity();
            entity.ReadFromXml(xml);

            entity.Should().BeEquivalentTo(new DerivedEntity
            {
                Id = 1,
                Name = "Base",
                Description = "Derived"
            });
        }

        [Fact]
        public void TestInheritance_BaseHasAttribute_Write()
        {
            var entity = new DerivedEntity
            {
                Id = 2,
                Name = "Test",
                Description = "Details"
            };

            var xml = entity.WriteToXml();

            xml.Element("Id")?.Value.Should().Be("2");
            xml.Element("Name")?.Value.Should().Be("Test");
            xml.Element("Description")?.Value.Should().Be("Details");
        }

        [Fact]
        public void TestInheritance_BaseNoAttribute()
        {
            var xml = new XElement("FlattenedEntity",
                new XElement("BaseId", 10),
                new XElement("ChildProperty", "Value"));

            var entity = new FlattenedEntity();
            entity.ReadFromXml(xml);

            entity.Should().BeEquivalentTo(new FlattenedEntity
            {
                BaseId = 10,
                ChildProperty = "Value"
            });
        }

        [Fact]
        public void TestInheritance_WithOptions()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.CamelCase
            };

            var xml = new XElement("DerivedEntity",
                new XElement("id", 3),
                new XElement("name", "CamelTest"),
                new XElement("description", "CamelDesc"));

            var entity = new DerivedEntity();
            entity.ReadFromXml(xml, options);

            entity.Should().BeEquivalentTo(new DerivedEntity
            {
                Id = 3,
                Name = "CamelTest",
                Description = "CamelDesc"
            });
        }
    }
}
