using System;
using System.IO;
using System.Xml.Linq;
using Xunit;
using XmlSourceGenerator.Abstractions;

namespace XmlSourceGenerator.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
    }

    public class OptionsTests
    {
        [Fact]
        public void TestPropertyOverride()
        {
            var options = new XmlSerializationOptions();
            options.PropertyOverrides[(typeof(Product), "ProductName")] = "FullProductName";

            var xml = new XElement("Product",
                new XElement("ProductId", 1),
                new XElement("FullProductName", "Widget"));

            var product = new Product();
            product.ReadFromXml(xml, options);

            Assert.Equal(1, product.ProductId);
            Assert.Equal("Widget", product.ProductName);
        }

        [Fact]
        public void TestCamelCaseNaming()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.CamelCase
            };

            var xml = new XElement("Product",
                new XElement("productId", 2),
                new XElement("productName", "Gadget"));

            var product = new Product();
            product.ReadFromXml(xml, options);

            Assert.Equal(2, product.ProductId);
            Assert.Equal("Gadget", product.ProductName);
        }

        [Fact]
        public void TestSnakeCaseNaming()
        {
            var options = new XmlSerializationOptions
            {
                PropertyNamingPolicy = XmlNamingPolicy.SnakeCase
            };

            var xml = new XElement("Product",
                new XElement("product_id", 3),
                new XElement("product_name", "Tool"));

            var product = new Product();
            product.ReadFromXml(xml, options);

            Assert.Equal(3, product.ProductId);
            Assert.Equal("Tool", product.ProductName);
        }

        [Fact]
        public void TestWriteIndented()
        {
            var product = new Product { ProductId = 1, ProductName = "Test" };
            
            var options = new XmlSerializationOptions { WriteIndented = true };

            using var stream = new MemoryStream();
            GenericXmlStreamer.WriteDataToStreamAsync(stream, new[] { product }, options).Wait();
            
            stream.Position = 0;
            var text = new StreamReader(stream).ReadToEnd();

            Assert.Contains("\n", text); // Should have newlines
            Assert.Contains("  ", text); // Should have indentation
        }

        [Fact]
        public void TestWriteMinified()
        {
            var product = new Product { ProductId = 1, ProductName = "Test" };
            
            var options = new XmlSerializationOptions { WriteIndented = false };

            using var stream = new MemoryStream();
            GenericXmlStreamer.WriteDataToStreamAsync(stream, new[] { product }, options).Wait();
            
            stream.Position = 0;
            var text = new StreamReader(stream).ReadToEnd();

            // Minified should not have extra whitespace
            Assert.DoesNotContain(">\n  <", text);
        }
    }
}
