using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Xunit;
using SourceGeneratorUtils;

namespace SourceGeneratorUtils.Tests.Integration
{
    [XmlAutoGenerated]
    public partial class LedgerEntry
    {
        public string LedgerName { get; set; }
    }

    [XmlAutoGenerated]
    public partial class AllLedgerEntry : LedgerEntry
    {
        public double Amount { get; set; }
    }

    [XmlAutoGenerated]
    public partial class Voucher
    {
        public int VoucherNumber { get; set; }

        [XmlStreamListElement("ALLLEDGERENTRIES.LIST", typeof(AllLedgerEntry))]
        [XmlStreamListElement("LEDGERENTRIES.LIST", typeof(LedgerEntry))]
        public List<LedgerEntry> LedgerEntries { get; set; } = new();
    }

    public class PolymorphismTests
    {
        [Fact]
        public void TestPolymorphicList_MixedTypes()
        {
            var xml = new XElement("Voucher",
                new XElement("VoucherNumber", 1001),
                new XElement("ALLLEDGERENTRIES.LIST",
                    new XElement("LedgerName", "Sales"),
                    new XElement("Amount", 5000.0)),
                new XElement("LEDGERENTRIES.LIST",
                    new XElement("LedgerName", "Purchase"))
            );

            var voucher = new Voucher();
            voucher.ReadFromXml(xml);

            Assert.Equal(1001, voucher.VoucherNumber);
            Assert.Equal(2, voucher.LedgerEntries.Count);
            
            Assert.IsType<AllLedgerEntry>(voucher.LedgerEntries[0]);
            Assert.Equal("Sales", voucher.LedgerEntries[0].LedgerName);
            Assert.Equal(5000.0, ((AllLedgerEntry)voucher.LedgerEntries[0]).Amount);

            Assert.IsType<LedgerEntry>(voucher.LedgerEntries[1]);
            Assert.Equal("Purchase", voucher.LedgerEntries[1].LedgerName);
        }

        [Fact]
        public void TestPolymorphicList_Write()
        {
            var voucher = new Voucher
            {
                VoucherNumber = 2001,
                LedgerEntries = new List<LedgerEntry>
                {
                    new AllLedgerEntry { LedgerName = "Income", Amount = 10000 },
                    new LedgerEntry { LedgerName = "Expense" }
                }
            };

            var xml = voucher.WriteToXml();

            var entries = xml.Elements().Where(e => e.Name.LocalName.Contains("LEDGER")).ToList();
            Assert.Equal(2, entries.Count);
            Assert.Equal("ALLLEDGERENTRIES.LIST", entries[0].Name.LocalName);
            Assert.Equal("LEDGERENTRIES.LIST", entries[1].Name.LocalName);
        }
    }
}
