using System;
using System.Collections.Generic;
using System.Xml.Linq;
using SourceGeneratorUtils;
using XmlSourceGenerator.Attributes;

namespace SourceGeneratorUtils
{
    // -------------------------------------------------------------------------
    // INPUT: User writes this
    // -------------------------------------------------------------------------
    [XmlAutoGenerated]
    public partial class Voucher
    {
        public int VoucherNumber { get; set; }

        [XmlStreamListElement("ALLLEDGERENTRIES.LIST", typeof(AllLedgerEntry))]
        [XmlStreamListElement("LEDGERENTRIES.LIST", typeof(LedgerEntry))]
        public List<LedgerEntry> LedgerEntries { get; set; } = new();
    }

    [XmlAutoGenerated]
    public partial class LedgerEntry
    {
        public string LedgerName { get; set; }
    }

    [XmlAutoGenerated]
    public partial class AllLedgerEntry : LedgerEntry
    {
        public double Amount { get; set; }
    }

    // -------------------------------------------------------------------------
    // OUTPUT: Source Generator produces this (Simulated)
    // -------------------------------------------------------------------------
    public partial class Voucher : IXmlStreamable
    {
        public void ReadFromXml(XElement element, XmlSerializationOptions options = null)
        {
            VoucherNumber = (int)element.Element("VoucherNumber");

            if (LedgerEntries == null) LedgerEntries = new();
            foreach (var child in element.Elements())
            {
                switch (child.Name.LocalName)
                {
                    case "ALLLEDGERENTRIES.LIST":
                        var item1 = new AllLedgerEntry();
                        if (item1 is IXmlStreamable streamable1) streamable1.ReadFromXml(child, options);
                        LedgerEntries.Add(item1);
                        break;
                    case "LEDGERENTRIES.LIST":
                        var item2 = new LedgerEntry();
                        if (item2 is IXmlStreamable streamable2) streamable2.ReadFromXml(child, options);
                        LedgerEntries.Add(item2);
                        break;
                }
            }
        }

        public XElement WriteToXml(XmlSerializationOptions options = null)
        {
            var element = new XElement("Voucher");
            if (VoucherNumber != default) element.Add(new XElement("VoucherNumber", VoucherNumber));

            if (LedgerEntries != null)
            {
                foreach (var item in LedgerEntries)
                {
                    if (item is AllLedgerEntry typedItem)
                    {
                        var child = ((IXmlStreamable)typedItem).WriteToXml(options);
                        child.Name = "ALLLEDGERENTRIES.LIST";
                        element.Add(child);
                    }
                    else if (item is LedgerEntry typedItem2)
                    {
                        var child = ((IXmlStreamable)typedItem2).WriteToXml(options);
                        child.Name = "LEDGERENTRIES.LIST";
                        element.Add(child);
                    }
                }
            }
            return element;
        }
    }

    public partial class LedgerEntry : IXmlStreamable
    {
        public void ReadFromXml(XElement element, XmlSerializationOptions options = null)
        {
            LedgerName = (string)element.Element("LedgerName");
        }

        public XElement WriteToXml(XmlSerializationOptions options = null)
        {
            var element = new XElement("LedgerEntry");
            if (LedgerName != default) element.Add(new XElement("LedgerName", LedgerName));
            return element;
        }
    }

    public partial class AllLedgerEntry : IXmlStreamable
    {
        public void ReadFromXml(XElement element, XmlSerializationOptions options = null)
        {
            base.ReadFromXml(element, options); // Inheritance handled!
            Amount = (double)element.Element("Amount");
        }

        public XElement WriteToXml(XmlSerializationOptions options = null)
        {
            var element = new XElement("AllLedgerEntry");
            var baseElement = base.WriteToXml(options);
            element.Add(baseElement.Attributes());
            element.Add(baseElement.Elements());
            
            if (Amount != default) element.Add(new XElement("Amount", Amount));
            return element;
        }
    }
}
