global using XmlAutoGeneratedAttribute = XmlSourceGenerator.Abstractions.XmlAutoGeneratedAttribute;
global using XmlStreamListElementAttribute = XmlSourceGenerator.Abstractions.XmlStreamListElementAttribute;
global using XmlFormatAttribute = XmlSourceGenerator.Abstractions.XmlFormatAttribute;
global using Xunit;
global using System.Xml.Linq;
global using System.Collections.Generic;
global using System.Linq;
global using System;
