namespace XmlSourceGenerator
{
    /// <summary>
    /// Centralized constants for magic strings used throughout the generator.
    /// </summary>
    internal static class Constants
    {
        // Namespaces
        public const string AbstractionsNamespace = "XmlSourceGenerator.Abstractions";
        
        // Attribute Names (fully qualified)
        public const string XmlAutoGeneratedAttributeFullName = "XmlSourceGenerator.Abstractions.XmlAutoGeneratedAttribute";
        
        // Interface Names
        public const string IXmlStreamableInterfaceName = "IXmlStreamable";
        
        // Method Names
        public const string ReadFromXmlMethodName = "ReadFromXml";
        public const string WriteToXmlMethodName = "WriteToXml";
        
        // Type Names
        public const string XmlSerializationOptionsTypeName = "XmlSerializationOptions";
        public const string XElementTypeName = "XElement";
        public const string XNamespaceTypeName = "XNamespace";
        
        // Nested Class Names
        public const string XmlTypeInfoClassName = "XmlTypeInfo";
        
        // Property Name Prefixes
        public const string PropNamePrefix = "PropName_";
        public const string DefaultXmlNamePrefix = "DefaultXmlName_";
        public const string NamespaceFieldPrefix = "Namespace";
        
        // Generated File Suffix
        public const string GeneratedFileSuffix = "_XmlGenerated.g.cs";
        
        // Using Directives
        public const string SystemNamespace = "System";
        public const string SystemCollectionsGenericNamespace = "System.Collections.Generic";
        public const string SystemXmlLinqNamespace = "System.Xml.Linq";
        public const string SystemGlobalizationNamespace = "System.Globalization";
    }
}
