using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorUtils
{
    [Generator]
    public class XmlSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is SyntaxReceiver receiver))
                return;

            var compilation = context.Compilation;
            var attributeSymbol = compilation.GetTypeByMetadataName("SourceGeneratorUtils.XmlAutoGeneratedAttribute");

            foreach (var classDeclaration in receiver.CandidateClasses)
            {
                var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDeclaration);

                if (classSymbol == null || !classSymbol.GetAttributes().Any(ad => SymbolEqualityComparer.Default.Equals(ad.AttributeClass, attributeSymbol)))
                    continue;

                string source = GenerateClass(classSymbol, compilation);
                context.AddSource($"{classSymbol.Name}_XmlGenerated.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private string GenerateClass(INamedTypeSymbol classSymbol, Compilation compilation)
        {
            var sb = new IndentedStringBuilder();
            
            string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Xml.Linq;");
            sb.AppendLine("using System.Globalization;"); // For DateTime parsing
            sb.AppendLine("using SourceGeneratorUtils;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            
            using (sb.Indent())
            {
                var parents = new Stack<INamedTypeSymbol>();
                var current = classSymbol.ContainingType;
                while (current != null)
                {
                    parents.Push(current);
                    current = current.ContainingType;
                }

                foreach (var parent in parents)
                {
                    sb.AppendLine($"partial class {parent.Name}");
                    sb.AppendLine("{");
                    sb.Indent();
                }

                sb.AppendLine($"public partial class {classSymbol.Name} : IXmlStreamable");
                sb.AppendLine("{");
                
                using (sb.Indent())
                {
                    // Generate nested XmlTypeInfo class
                    sb.AppendLine("private static class XmlTypeInfo");
                    sb.AppendLine("{");
                    using (sb.Indent())
                    {
                        sb.AppendLine($"public static readonly Type Type = typeof({classSymbol.ToDisplayString()});");
                        
                        var properties = PropertyHelpers.GetAllProperties(classSymbol);
                        
                        // Generate property name constants
                        foreach (var prop in properties)
                        {
                            if (prop.IsStatic) continue;
                            sb.AppendLine($"public const string PropName_{prop.Name} = nameof({classSymbol.ToDisplayString()}.{prop.Name});");
                        }
                        
                        // Generate default XML name constants (eliminates string literals in generated code)
                        foreach (var prop in properties)
                        {
                            if (prop.IsStatic) continue;
                            sb.AppendLine($"public const string DefaultXmlName_{prop.Name} = \"{prop.Name}\";");
                        }
                        
                        // Generate namespace constants
                        var uniqueNamespaces = new System.Collections.Generic.HashSet<string>();
                        
                        // Check root namespace
                        string? rootNs = XmlNamespaceHelper.GetNamespace(classSymbol);
                        if (rootNs != null)
                        {
                            uniqueNamespaces.Add(rootNs);
                        }
                        
                        // Check property namespaces
                        foreach (var prop in properties)
                        {
                            if (prop.IsStatic) continue;
                            string? propNs = XmlNamespaceHelper.GetNamespace(prop);
                            if (propNs != null)
                            {
                                uniqueNamespaces.Add(propNs);
                            }
                        }
                        
                        // Generate namespace fields
                        int nsIndex = 0;
                        var namespaceMap = new System.Collections.Generic.Dictionary<string, string>();
                        foreach (var ns in uniqueNamespaces)
                        {
                            string fieldName = $"Namespace{nsIndex}";
                            namespaceMap[ns] = fieldName;
                            sb.AppendLine($"public static readonly XNamespace {fieldName} = XNamespace.Get(\"{ns}\");");
                            nsIndex++;
                        }
                    }
                    sb.AppendLine("}");
                    sb.AppendLine();

                    new XmlReadGenerator(sb, compilation).GenerateReadMethod(classSymbol);
                    sb.AppendLine();
                    new XmlWriteGenerator(sb, compilation).GenerateWriteMethod(classSymbol);
                }

                sb.AppendLine("}");

                foreach (var parent in parents)
                {
                    sb.DecrementIndent();
                    sb.AppendLine("}");
                }
            }
            sb.AppendLine("}");

            return sb.ToString();
        }

        class SyntaxReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
                    classDeclaration.AttributeLists.Count > 0)
                {
                    CandidateClasses.Add(classDeclaration);
                }
            }
        }
    }
}
