using System;

namespace SourceGeneratorUtils
{
    /// <summary>
    /// Specifies derived types that can appear when serializing/deserializing the declaring class.
    /// Enables polymorphism without explicit property mappings.
    /// </summary>
    /// <example>
    /// <code>
    /// [XmlInclude(typeof(Dog))]
    /// [XmlInclude(typeof(Cat))]
    /// [XmlAutoGenerated]
    /// public partial class Animal
    /// {
    ///     public string Name { get; set; }
    /// }
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    public class XmlIncludeAttribute : Attribute
    {
        /// <summary>
        /// Gets the type that can be substituted for the declaring class.
        /// </summary>
        public Type Type { get; }

        public XmlIncludeAttribute(Type type)
        {
            Type = type ?? throw new ArgumentNullException(nameof(type));
        }
    }
}
